# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('ans_type', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=400)),
            ],
        ),
    ]
